# Site settings
title: Android_大船
email: clipperL@126.com
description: > # this means to ignore newlines until "baseurl:"
  clipperl's blog
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://clipperl.top/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  clipperL

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title.html